sudo: false
language: ruby
script: ruby -rubygems -rbundler/setup -S rake spec
rvm:
  - jruby-1.7.8
branches:
  only:
    - master
    - 2.x-dev
    - /^test-.*/
env:
  - JRUBY_OPTS="--1.8 --server -Xcext.enabled=false -Xcompile.invokedynamic=false"
  - JRUBY_OPTS="--1.9 --server -Xcext.enabled=false -Xcompile.invokedynamic=false"
matrix:
  include:
    - rvm: jruby-head
      env: JRUBY_OPTS="--server -Xcext.enabled=false -Xcompile.invokedynamic=false"
    - rvm: jruby-1.7.20
      env: JRUBY_OPTS="--server -Xcext.enabled=false -Xcompile.invokedynamic=false"
    - rvm: 1.8.7
      env: ''
    - rvm: 1.9.2
      env: ''
    - rvm: 1.9.3
      env: ''
    - rvm: jruby
      env: MAVEN_OPTS="-XX:MaxPermSize=128m"
      script: mvn clean verify
  allow_failures:
    - rvm: jruby
    - rvm: jruby-head
notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
